---
- hosts: test
  gather_facts: yes
  remote_user: root

  tasks:
    - name: Create a login
      user:
        name: user1
        password: "{{ 'password' | password_hash('sha512', 'root') }}"
#        groups:
#          - docker
#          - sudo
        state: present
        shell: /bin/bash       
        system: no             
        createhome: yes      
        home: /home/user1

    - name: Generate SSH-password
      user:
        name: user1
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/user1/.ssh/id_rsa

    - name: authorized key
      authorized_key:
        user: user1
        state: present
        key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
