---
- name: Install MySQL 
  gather_facts: yes
  hosts: test
  
  tasks:
    - name: "Installing Repo"
      shell: sudo rpm -Uvh http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
      ignore_errors: yes
    - name: "Installing MySQL 5.7"
      package: name=mysql-community-server state=present
    - name: Start the MySQL service
      become: yes
      service: 
        name: mysqld
        state: started
        enabled: yes

