---
# tasks file for nginx_2
- name: install nginx
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: nginx conf template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
